### PR TITLE
Migrate dependency management from deprecated Godep to dep

### PR DESCRIPTION
**Pull request by gviedma**
Since Godep has been deprecated and replaced by dep, it makes sense to migrate certstrap to use a supported dependency management system. New projects like mine that have embraced dep cannot import old Godep based dependencies, which is blocking adoption of certstrap.

### CODE REVIEW

**Comment by gviedma** [comment]
Note that the tests fail on go 1.5 but pass otherwise. I'm wondering if deprecating 1.5 is a feasible option here.

**Comment by csstaub** [comment]
Hi @gviedma, thanks for the pull request! We can just drop support for Go 1.5, and actually we should probably just require Go 1.11 I think.

**Comment by gviedma** [comment]
Thanks for the tip @csstaub  ! I've done as you suggested, dropped golang 1.5, and set golang 1.11 as the default. CI is happy now.

**Comment by gviedma** [comment]
I decided to submit this PR because my dep-based project is unable to resolve Godep dependencies such as those imported by certstrap. Without a move to dep, I'd be forced to import a forked version. I imagine this is a blocker for anybody out there using dep.

I'm not aware of that many projects using modules yet, so it might be worth having an intermediate release with just the dep migration first for those who don't need/want modules or aren't driving go 1.11 ir later.

**Comment by mcpherrinm** [comment]
OK.  I don't see any particular reason to not merge this, as you've already done the hard work :)

We can revisit go modules when they're non-experimental

**Pull request merged**
