### PR TITLE
Add revoke command

### PR DESCRIPTION
**Pull request by namreg**
Resolve https://github.com/square/certstrap/issues/43.
Any comments are appreciated.

### CODE REVIEW

**Comment by mcpherrinm** [comment]
Thanks!  I'll review soon.  It looks fine from a high level overview

**Comment by mcpherrinm** [comment]
Sorry this has hung around for so long (the last month has been busy).

The only real concern I have with this PR is a lack of tests.  I'm not too worried about that for now, but would appreciate at least a basic functional test.

note that we just merged another PR moving away from Godep and this will require your PR to be updated too.

**Comment by namreg** [comment]
@mcpherrinm Got it! I will add some tests asap and let you know when done.

**Comment by namreg** [comment]
@mcpherrinm I have done

**Comment by mcpherrinm** [comment]
One more nit:  You've check in the `certstrap` binary.  Please remove it from your PR (including from history) so as to not bloat this repo.

It would be nice if there was an option on the revoke command to revoke by serial (in case you don't have the cert file), but we can merge without that and add it in the future.

Otherwise I think we can merge.

**Comment by namreg** [comment]
@mcpherrinm I've removed `certstrap ` binary, also rebased on master and squashed commits.

**Comment by mcpherrinm** [comment]
Great!  Thank you for your contribution

**Pull request merged**
