### PR TITLE
Support x86_64 or s390x architecture

### PR DESCRIPTION
**Pull request by jeffchi**

### CODE REVIEW

**Comment by mbyczkowski** [comment]
@jeffchi do you have a particular use-case for `s390x`? `x86_64` is already supported and in Go it's called `amd64`.

**Comment by jeffchi** [comment]
@mbyczkowski  

The PR is to build the certstrap utility on a Linux instance running on IBM Z or LInuxONE.

**Comment by mcpherrinm** [comment]
Given the obscurity of s390x, and our own inability to test, I'm pretty hesitant to accept this.  I don't think I'd want to release s390x binaries without anywhere to test them, and 

I would be happy to accept any blockers to actually using certstrap there, but I don't think it needs to be in the build script.
On non-supported platforms you can use the go build tools as normal.  We should probably indicate how to do that in the README, though it's standard Go stuff.

**Comment by mcpherrinm** [comment]
in #109, the instructions were updated to remove references to the build script, though it's still used in CI.

Since we don't have s390x machines in CI or to test on, we can't reasonably claim it's a supported platform.  However, I don't see any reason it wouldn't work.  Feel free to open specific bugs or PRs if it doesn't.

**Pull request closed without merging**
