### PR TITLE
certstrap: Get rid of vendoring

### PR DESCRIPTION
**Pull request by defer**
Now that certstrap is built on go1.11 with modules support, we don't
need to keep these around. We also don't need to establish a go
environment as subfolder for building.

### CODE REVIEW

**Comment by mcpherrinm** [comment]
I think we'd like to keep vendoring around for the near future, until the ecosystem matures a bit

**Comment by mbyczkowski** [comment]
I agree. Go modules will be turned on by default in Go 1.13, so let's wait at least until then.

**Comment by defer** [comment]
Sounds like a plan 👍

**Comment by mbyczkowski** [comment]
@defer if you're still interested, now is probably a good time to dust off your PR and get rid off vendoring :)

**Comment by mcpherrinm** [comment]
#93 removed vendorized deps

**Pull request closed without merging**
